site:
  title: Hos's blog
  start_page: home-page::index.adoc
content:
  sources:

  # - url: ../antora/perl
  #   branches: antora/perl
  #   start_paths: /
  # - url: ../antora/golang
  #   branches: antora/golang
  #   start_paths: /

  - url: https://github.com/hossein-lap/blog.git
    branches: antora/home
    start_paths: /

  - url: https://github.com/hossein-lap/blog.git
    branches: antora/perl
    start_paths: /
  - url: https://github.com/hossein-lap/blog.git
    branches: antora/golang
    start_paths: /

  # - url: https://gitlab.com/hos-blog/antora.git
  #   branches: perl
  #   start_paths: .
  # - url: https://gitlab.com/hos-blog/antora.git
  #   branches: golang
  #   start_paths: .

runtime:
  cache_dir: ./cache/antora


ui:
  bundle:
    # url: https://gitlab.com/hos-blog/antora-ui-hos/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/hossein-lap/asciidoctor-docs-ui/releases/download/prod-350/ui-bundle.zip

    snapshot: true
asciidoc: 
  attributes: 
    skip-front-matter: true
    icons: font
    icon-set: fi
    sectnums: true
    toc: false
    source-highlighter: pygments
    pygments-style: solarized-light
    # highlightjs-theme: tomorrow-night
