baseURL: "https://hossein-lap.github.io"
theme: "allgray"
# theme: "hugo-ficurinia"
title: "primejade"
languageCode: "en-us"
defaultContentLanguage: "en"


params:
  author: "primejade"
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext: "Related"
  favicon: "/favicon.ico"

  # github: hossein-lap
  # gitlab: primejade
  # codeberg: primejade
  # email: hosteam01@gmail.com

  # list items
  datesinlist: true
  authorsinlist: true

  # footer items
  nextprev: true
  taglist: true
  showrss: true

  custom_css:
    - "/fonts/fonts.css"
    - "/css/syntax.css"
    - "/css/style.css"

# markup:
#   goldmark:
#     renderer:
#       # enable using html in md files
#       unsafe: true
#   highlight:
#     noClasses: true
#     lineNos: true
#     lineNumbersInTable: false
#     anchorLineNos: false
#     lineAnchors: ""
#     style: "gruvbox"
#     codeFences: true
#     guessSyntax: false
#     hl_Lines: ""
#     hl_inline: false
#     lineNoStart: 1
#     noHl: false
#     tabWidth: 8

# Top Menu Example
menu:
  main:
    - Name: "P J"
      URL: "/"
      weight: 1
    # - Name: "Progamming"
    #   URL: "/programming"
    #   weight: 1
    # - Name: "RSS"
    #   URL: "/index.xml"
    #   weight: 2
    # - Name: "Tags"
    #   URL: "/tags"
    #   weight: 3


markup:
  markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  asciidocExt:
    options:
      safe: "unsafe"
    attributes:
      # numbered: true
      icons: font
      source-highlighter: "rouge"
      rouge-style: "base16.dark"
      rouge-css: "syntax"

security:
  enableInlineShortcodes: true
  exec:
    allow:
      - "^dart-sass-embedded$"
      - "^go$"
      - "^npx$"
      - "^postcss$"
      - "^asciidoctor$"
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"

