title: "Hossein Esmail"
baseURL: "hossein-lap.github.io"
languageCode: "en-us"
theme: "allgray"
params:
  favicon: /favicon
  relatedtext: Tags
  dateinlist: true
  authorlist: true
  nextprev: true
  taglist: true
  showrss: false
  custom_css: ["/css/syntax.css", "/css/style.css", "/css/theme.css"]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: true
    lineNos: true
    lineNumberInTable: false
    anchorLineNos: false
    lineAnchors: ""
    style: gruvbox
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineNoStart: 1
    noHl: false
    tabWidth: 8
menu:
  main:
    - name: primejade
      url: "/"
      weight: 1
    - name: RSS
      url: "/index.xml"
      weight: 2
    - name: Tags
      url: "/tags"
      weight: 3
