# https://gohugo.io/getting-started/configuration/

baseURL = "https://hossein-lap.gitgub.io"

title = "Hossein Esmail"
# copyright = "Brice Dutheil — All rights reserved."

theme = "ascii-press"

# generate robots.txt
enableRobotsTXT = true

# googleAnalytics = "your-google-analytics-id"

languageCode = "en-US"

# Content without language indicator will default to this language.
defaultContentLanguage = "en"

# Render the default content language in subdir, e.g. content/en/.
# The site root / will then redirect to /en/.
# defaultContentLanguageInSubdir = false


summarylength = 30

canonifyURLs = true
preserveTaxonomyNames = true

# Remove accents from URL, otherwise they appear as url-encoded
removePathAccents = true

# Configure pagination
paginate = 22
paginatePath = "page"



# Enable Emoji emoticons support for page content
# See https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji = true


timeout = 60000

[markup]
#     [markup.goldmark]                   # This is the markdown rendered
#         [markup.goldmark.renderer]
#             unsafe = true               # Allow html (needed for some shortcodes)

    [markup.highlight]
        codeFences = false               # Disables goldmark chroma syntax highlighter

[markup.asciidocext]
    extensions = ["asciidoctor-diagram"]
    workingFolderCurrent = true
    trace = true
    failureLevel = "fatal"

    preserveTOC = false # for debug

    [markup.asciidocext.attributes]
        "toc" = ""
        "toc-title!" = "Simple test"
        "toc-level" = "2"
        "docinfo" = "shared"
        "nofooter" = ""
        "skip-front-matter" = ""
        "library" = "asciidoctor-ruby"
        "icons" = "font"
        "sectlinks" = ""
        "sectanchors" = ""
        "figure-caption!" = ""
        "source-highlighter" = "highlightjs"
        "experimental" = "true"
        "plantuml-format" = "svg" # https://github.com/asciidoctor/asciidoctor-diagram/commit/642f17283834405088d6784e95d8b8dac62c17dc
        "ditaa-format" = "svg"
        "diagram-svg-type" = "inline"
        "image-assets" = "/assets"
#        "imagesoutdir" = ""
#        "diagram-imagesdir" = ".asciidoctor/diagram"
#        "cachedir" = ".asciidoctor/diagram"
#        "diagram-autoimagesdir" = ""
#        "imagesdir" = "/"
        "allow-uri-read" = "" # Enable link includes

[outputFormats]
    [outputFormats.manifest]
        name = "manifest"
        baseName = "manifest"
        mediaType = "application/json"
        notAlternative = "true"
    [outputFormats.browserconfig]
        name = "browserconfig"
        baseName = "browserconfig"
        mediaType = "application/xml"
        notAlternative = "true"

[outputs]
    home = [ "HTML", "RSS", "MANIFEST", "BROWSERCONFIG"]

[author]
    name = "Hossein Esmailzadeh"
    email = "hosteam01@gmail.com"
    # twitter = "BriceDutheil"

# for use in templates
## Site Settings
[params]
    author = "Hossein Esmail"
    title = "Personal Blog"
    authorimage = "/images/me/me-circle.png"
    # Site description
    description = "Linux, Vim, Programming stuff"


    ### Twitter card / open graph
    # Modified from universal theme
    # https://github.com/devcows/hugo-universal-theme/blob/232f219ee77aee3b539ed18417c02e328c3b4630/layouts/partials/head.html#L59-L101
    # https://github.com/devcows/hugo-universal-theme#meta-tags
    images = ["/android-192-favicon.png"]
    default_sharing_image = "/images/me/me-circle.png"
    defaultKeywords = ["linux", "vim", "asciidoc"]
    defaultDescription = "Linux, Vim, Programming stuff"
    # twitter_author = "BriceDutheil"
    # twitter_site = "BriceDutheil"
    ###

    # Favicon file (relative to baseURL - place below static or assets folder)
    # favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    # css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateformat = "2006-01-02"

    # # sidebar, copyright & license
    # copyright = "primejade"
    # since = 2010
    # license = "CC BY-SA 4.0"
    # licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    # showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "a11y-light"
    highlightjsdarkstyle = "base16/gruvbox-dark-medium"
    # highlightjslanguages = ["..."]

    # Table of contents
    #toc = none, "hugo", or "tocbot" (for tocboot configuration : layouts/partials/page-single/footer.html)
    toc = "hugo"

    mainSections = ["blog"]

    landingLastPosts = 10

    taxonomyIndexThreshold = 20

    githubEdit= "https://github.com/hossein-lap/hossein-lap.github.io/edit/hugo-sources/content/"

## Social Accounts
[params.social]
    github = "hossein-lap"
    # speakerdeck = "bric3"
    linkedin = "hossein-esmail"
    # twitter = "BriceDutheil"
    # stackoverflow = "48136/brice"
    email = "hosteam01@gmail.com"
    # gravatar = "brice.dutheil@gmail.com"
    mastodon = "https://mastodon.xyz/@BriceDutheil"

[params.giscus]
    repo = "hossein-lap/hossein-lap.github.io"
    repoId = "MDEwOlJlcG9zaXRvcnk2MDc3NjczMQ=="
    category = "Blog Comments"
    categoryID = "DIC_kwDOA59hG84CR_S_"
    mapping = "pathname"
    reactions = true
    inputPosition = "top"
    theme = "preferred-color-scheme"

[permalinks]
    posts = "/:year/:month/:day/:slug/"
    drafts = "/:section/:year/:month/:day/:slug/"

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"



[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0


[menu]
    [[menu.main]]
        # name = "Home"
        # pre = "<span class='fa-icon'><i class='fas fa-home'></i></span><code>cd <em>~</em></code>"
        pre = "<span class='fa-icon'><i class='fas fa-home'></i></span><code>home</code>"
        url = "/"
        weight = -100

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "blog"
        # name = "Posts"
        title = "All posts"
        pre = "<span class='fa-icon'><i class='fas fa-stream'></i></span><code>blog</code>"
        # pre = "<i class='fas fa-blog'></i> <code>ls posts/*</code>"
        # pre = "<i class='far fa-newspaper'></i> <code>ls posts/*</code>"
        url = "/docs/"
        weight = 1

    [[menu.main]]
        identifier = "notes"
        # name = "Cool stuff"
        pre = "<span class='fa-icon'><i class='fas fa-thumbtack'></i></span><code>notes</code>"
        title = "Notes"
        weight = 2
        url = "/notes/"

    # [[menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     title = "All categories"
    #     url = "/categories/"
    #     weight = 3

    [[menu.main]]
        identifier = "series"
        # name = "Series"
        pre = "<span class='fa-icon'><i class='fas fa-list-alt'></i></span><code>series</code>"
        # pre = "<i class='fa fa-object-group'></i> <code>grep posts/* series | sort | uniq</code>"
        title = "All series"
        url = "/series/"
        weight = 3

    [[menu.main]]
        identifier = "tags"
        # name = "Tags"
        pre = "<span class='fa-icon'><i class='fas fa-tags'></i></span><code>tags</code>"
        title = "All tags"
        url = "/tags/"
        weight = 4

    [[menu.main]]
        identifier = "Me."
        # name = "Who Am I ?"
        pre = "<span class='fa-icon'><i class='fas fa-id-card'></i></span><code>Me</code>"
        title = "About me"
        weight = 5
        url = "/me/"

    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/bric3/bric3.github.io"
        weight = 1

# [params.search]
# client = "fuse" # algolia / fuse / lunr

# [languages]
#     # edit this block for your own language
#     [languages.en]
#         lang = "en"
#         languageName = "English"
#         # weight = 1
#
#     # [languages.fr]
#         # lang = "fr"
#         # languageName = "French"
#         # weight = 1

[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
